### ISSUE TITLE
Exercices d'approfondissement

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/formation-bonnes-pratiques-R#9]
- [x] Package
- [ ] Docker
- [ ] Intégration continue (sur linter et test de la fonction `stats_agregees`)

**Comment by avouacr** [comment]
La partie sur les packages est faite dans 2e275faeaf570bf105959e774ef7fea691833a3a et 4eec9fcc1abf094cfbc4003e82fd574f4e940b63. Les apps sur Docker et le CI feront l'objet d'une formation à part
